### ISSUE TITLE
Create checklist for validation of raster datasets

### ISSUE THREAD

**Issue by ricardogsilva** [dominodeorg/dominode-qgis-resources#3]
The proposed workflows for data management in GeoNode mandate that datasets must be validated before being moved to the production areas.

In order to assist in this validation phase we are providing several checklist files to be used together with the [QGIS Dataset QA Workbench plugin].

Create a general raster validation checklist file that shall be later refined according to each department's needs. Follow these instructions

- Create a `raster-datasets.json` checklist file in the `collections/dominode-resources/checklists` directory of this repo

- Include checklist checks for validating a dataset's:

   - spatial correctness

     - [ ] Check that the CRS of the dataset is one of the official ones

     - [ ] Check that the bounds of the dataset cover Dominica

   - optimization of access

     - [ ] Check that dataset is a cloud-optimized geotiff. Two options:

       - Use the `validate_cloud_optimized_geotiff.py` script provided at the [cogeo website](https://www.cogeo.org/developers-guide.html)

       - Manually check the properties of the raster. Take a look at the source code for the python script referenced above for details:

          - tiling

          - overviews

          - compression

          - IFD offset

- Ideally checklist checks should be automated. If not possible, they can be manual. If needed, create additional processing models to aid in this process

[QGIS Dataset QA Workbench plugin]: https://github.com/kartoza/qgis_dataset_qa_workbench/
